# Generated by Django 4.2.4 on 2023-08-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='wallpaper',
            field=models.ImageField(blank=True, default='wallpaper/wallpaper.jpg', max_length=200, null=True, upload_to='wallpaper/'),
        ),
    ]
