# Generated by Django 4.2.4 on 2023-08-16 12:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminapp', '0002_customer_wallpaper'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Profileadmin',
        ),
    ]
