# Generated by Django 4.2.4 on 2023-08-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_rename_customer_profileadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileadmin',
            name='phone_field',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
