# Generated by Django 4.2.4 on 2023-08-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_alter_profileadmin_phone_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileadmin',
            name='about_me',
            field=models.TextField(blank=True, null=True),
        ),
    ]
